### ISSUE TITLE
Actobotics Parts

### ISSUE THREAD

**Issue by TheSiebi** [blee1170/SpacePointer#1]
Hello there! First of all: awesome project! But now to my question, would you be able to provide a parts list of the Actobotics parts you used? Would help me a lot!

Cheers

**Comment by LordBrain** [comment]
Sorry for the delay. I was on vacation. I updated the readme to include the parts I used: 

https://github.com/blee1170/SpacePointer#actobotics-parts

**Comment by TheSiebi** [comment]
Awesome! Thank you very much :)
